### ISSUE TITLE
Void & Refund missing from EwayRapidDirect

### ISSUE THREAD

**Issue by alexw23** [thephpleague/omnipay-eway#10]
Working on a fix for this

Tag: @incarnate

**Comment by incarnate** [comment]
@alexw23 looks like we did miss pre-auth void, thanks.

[Refund](https://github.com/thephpleague/omnipay-eway/blob/master/src/Message/RefundRequest.php) is [implemented](https://github.com/thephpleague/omnipay-eway/blob/master/src/RapidDirectGateway.php#L156)

**Comment by alexw23** [comment]
Sorry refund is implemented - the file names are getting a little bit confusing as we also have Rapid.

**Comment by alexw23** [comment]
See #11
