### ISSUE TITLE
Create / Update Tokens through RapidShared

### ISSUE THREAD

**Issue by fryiee** [thephpleague/omnipay-eway#20]
You can create tokens through the Responsive Shared Page in the Rapid API, but it looks like this isn't currently possible using the RapidShared Gateway. Is this something that will need to be PR'd in?

**Comment by incarnate** [comment]
Those methods are missing from the Rapid Shared gateway at the moment, yes

**Comment by fryiee** [comment]
I'm working on this now, and will submit a PR for it soon.

**Comment by fryiee** [comment]
See https://github.com/thephpleague/omnipay-eway/pull/21

**Comment by delatbabel** [comment]
Merged #21
